
const ads = [
  [
    'PROGRAMAÇÃO EM MICROINFORMÁTICA',
    'SISTEMAS DE INFORMAÇÃO',
    'ALGORÍTMOS E LÓGICA DE PROGRAMAÇÃO',
    'ARQUITETURA E ORGANIZAÇÃO DE COMPUTADORES ',
    'ADMINISTRAÇÃO GERAL',
    'MATEMÁTICA DISCRETA',
    'COMUNICAÇÃO E EXPRESSÃO',
    'INGLÊS I'
  ],
  [
    'ENGENHARIA DE SOFTWARE I',
    'LINGUAGEM DE PROGRAMAÇÃO',
    'ELETIVA I',
    'LABORATÓRIO DE HARDWARE',
    'SISTEMAS OPERACIONAIS I',
    'ESTATÍSTICA APLICADA',
    'CÁLCULO',
    'CONTABILIDADE',
    'INGLÊS II'
  ],
  [
    'ENGENHARIA DE SOFTWARE II',
    'ESTRUTURAS DE DADOS',
    'INTERAÇÃO HUMANO COMPUTADOR',
    'ELETIVA II',
    'SISTEMAS OPERACIONAIS II',
    'BANCO DE DADOS',
    'PROGRAMAÇÃO LINEAR E APLICAÇÕES',
    'ECONOMIA E FINANÇAS',
    'INGLÊS III',
  ],
  [
    'ENGENHARIA DE SOFTWARE III',
    'PROGRAMAÇÃO ORIENTADA A OBJETOS',
    'ESCOLHA I',
    'REDES DE COMPUTADORES',
    'GESTÃO DE PROJETOS',
    'SEGURANÇA DA INFORMAÇÃO',
    'SOCIEDADE E TECNOLOGIA',
    'INGLÊS IV',
  ],
  [
    'LABORATÓRIO DE ENGENHARIA DE SOFTWARE',
    'ESCOLHA II',
    'GESTÃO DE EQUIPES',
    'EMPREENDEDORISMO',
    'METODOLOGIA DA PESQUISA CIENTÍFICO-TECNOLÓGICA',
    'INGLÊS V',
    'TRABALHO DE GRADUAÇÃO I'
  ],
  [
    'ESCOLHA III',
    'GESTÃO E GOVERNANÇA DE TECNOLOGIA DE INFORMAÇÃO',
    'ÉTICA E RESPONSABILIDADE PROFISSIONAL',
    'INGLÊS VI',
    'TRABALHO DE GRADUAÇÃO II',
    'ESTÁGIO SUPERVISIONADO'
  ]
]

export default ads;